apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: sam2236/flask-mongodb-app
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb://admin:password@mongodb:27017/flask_db?authSource=admin"
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
